---
- name: Add/Modify/Remove pool member
  bigip_pool_member:
    server: "{{ f5server }}"
    user: "{{ f5user }}"
    password: "{{ f5password }}"
    validate_certs: "no"
    state: "{{ f5state }}"
    session_state: "{{ f5session_state }}"
    monitor_state: "{{ f5monitor_state }}"
    pool: "{{ f5pool }}"
    host: "{{ inventory_hostname }}"
    port: "{{ f5port }}"
    description: "{{ f5description }}"
#    connection_limit: "{{ f5connection_limit }}"
#    rate_limit: "{{ f5rate_limit }}"
#    ratio: "{{ f5ratio }}"
  delegate_to: localhost
...