---
# Get F5 credentials from user
- hosts: us5,sc5,au1,mun
  gather_facts: false
  roles:
    - f5-get-credentials
  vars_prompt:
    - name: "f5_user"
      prompt: "Enter your F5 username"
      private: no
    - name: "f5_password"
      prompt: "Enter your F5 password"
      private: yes
#      confirm: yes
#      encrypt: "sha512_crypt"
  tags:
    always

# Add nodes to the F5 in a disabled state
- hosts: addmembers
  gather_facts: false
  roles:
    - f5-node-add
  vars:
    f5_node_state: present
    f5_node_session_state: disabled
    f5_node_monitor_state: enabled
  tags:
    addnodedisabled

# Add nodes to the F5 in an enabled state
- hosts: addmembers
  gather_facts: false
  roles:
    - f5-node-add
  vars:
    f5_node_state: present
    f5_node_session_state: enabled
    f5_node_monitor_state: enabled
  tags:
    addnode

# Add node members to a pool
- hosts: addmembers
  gather_facts: false
  roles:
    - f5-pool-member-add
  vars:
    f5_node_state: present
    f5_node_session_state: enabled
    f5_node_monitor_state: enabled
  tags:
    addpoolmember

# Disable old members before removing them from the pool
- hosts: delmembers
  gather_facts: false
  vars:
    f5_node_state: present
    f5_node_session_state: disabled
    f5_node_monitor_state: disabled
  roles:
    - f5-pool-member-del
  tags:
    disablepoolmember

# Wait for 1 hour
- hosts: delmembers
  gather_facts: false
  roles:
    - f5-wait
  tags:
    wait

# Confirm connections have been drained
#- hosts: delmembers
#  gather_facts: false
#  vars:
#    ansible_user: "{{ f5_user }}"
#    ansible_pass: "{{ f5_password }}"
#  roles:
#    - f5-validate-drained
#  tags:
#    f5_drain

# Remove old members from the pool
- hosts: delmembers
  gather_facts: false
  vars:
    f5_node_state: absent
    f5_node_session_state: disabled
    f5_node_monitor_state: disabled
  roles:
    - f5-pool-member-del
  tags:
    delpoolmember

# Delete old members from the F5
- hosts: delmembers
  gather_facts: false
  roles:
    - f5-node-del
  vars:
    f5_node_state: absent
    f5_node_session_state: disabled
    f5_node_monitor_state: disabled
  tags:
    delnode
...