---
- wait_for: host={{ f5ip }} port={{ f5port }} timeout=1800 state=drained
  delegate_to: "{{ f5ip }}"
    #host: "{{ inventory_hostname }}"
    #port: "{{ f5port }}"
    #state: drained
- meta: clear_host_errors
...