---
- name: Remove node from f5_
  bigip_node:
    server: "{{ f5_hostname }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    validate_certs: "no"
    state: "absent"
    name: "{{ inventory_hostname }}"
  delegate_to: localhost
...