---
- name: Remove pool member
  bigip_pool_member:
    server: "{{ f5_hostname }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    validate_certs: "no"
    state: "{{ f5_state }}"
    session_state: "{{ f5_session_state }}"
    monitor_state: "{{ f5_monitor_state }}"
    pool: "{{ f5_pool }}"
    host: "{{ inventory_hostname }}"
    port: "{{ f5_port }}"
    description: "{{ f5_description }}"
  delegate_to: localhost
...