---
- name: Add node to F5
  bigip_node:
    server: "{{ f5server }}"
    user: "{{ f5user }}"
    password: "{{ f5password }}"
    validate_certs: "no"
    state: "present"
    host: "{{ f5ip }}"
    name: "{{ inventory_hostname }}"
    description: "{{ f5description }}"
  delegate_to: localhost
...